import { provideHttpClient } from '@angular/common/http';
import { ApplicationConfig, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';
import { provideRouter } from '@angular/router';
import {
  AppstoreOutline,
  ArrowRightOutline,
  AuditOutline,
  BarChartOutline,
  BellOutline,
  BookOutline,
  CalendarOutline,
  CameraOutline,
  CheckSquareOutline,
  DeleteOutline,
  EditOutline,
  FileTextOutline,
  FormOutline,
  HomeOutline,
  InfoCircleOutline,
  KeyOutline,
  LockOutline,
  LoginOutline,
  LogoutOutline,
  MailOutline,
  MenuOutline,
  PlusOutline,
  ReadOutline,
  ReloadOutline,
  RobotOutline,
  SettingOutline,
  SolutionOutline,
  StarOutline,
  SwapOutline,
  TeamOutline,
  TrophyOutline,
  UserAddOutline,
  UserOutline,
  WarningOutline,
} from '@ant-design/icons-angular/icons';
import { provideNzI18n, vi_VN } from 'ng-zorro-antd/i18n';
import { provideNzIcons } from 'ng-zorro-antd/icon';
import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideAnimationsAsync(),
    provideRouter(routes),
    provideHttpClient(),
    provideNzI18n(vi_VN),
    provideNzIcons([
      AppstoreOutline,
      ArrowRightOutline,
      AuditOutline,
      BarChartOutline,
      BellOutline,
      BookOutline,
      CalendarOutline,
      CameraOutline,
      CheckSquareOutline,
      DeleteOutline,
      EditOutline,
      FileTextOutline,
      FormOutline,
      HomeOutline,
      InfoCircleOutline,
      KeyOutline,
      LockOutline,
      LoginOutline,
      LogoutOutline,
      MailOutline,
      MenuOutline,
      PlusOutline,
      ReadOutline,
      ReloadOutline,
      RobotOutline,
      SettingOutline,
      SolutionOutline,
      StarOutline,
      SwapOutline,
      TeamOutline,
      TrophyOutline,
      UserAddOutline,
      UserOutline,
      WarningOutline,
    ]),
  ],
};
