import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { ApplicationConfig, inject, provideAppInitializer, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';
import { provideRouter } from '@angular/router';
import {
  AppstoreOutline,
  ArrowRightOutline,
  AuditOutline,
  BarChartOutline,
  BellOutline,
  BookOutline,
  CalendarOutline,
  CameraOutline,
  CheckCircleOutline,
  CheckSquareOutline,
  DeleteOutline,
  EditOutline,
  FileTextOutline,
  FormOutline,
  HomeOutline,
  InboxOutline,
  InfoCircleOutline,
  KeyOutline,
  LockOutline,
  LoginOutline,
  LogoutOutline,
  MailOutline,
  MenuOutline,
  PlusOutline,
  ReadOutline,
  ReloadOutline,
  RobotOutline,
  SearchOutline,
  SettingOutline,
  SolutionOutline,
  StarOutline,
  SwapOutline,
  TeamOutline,
  TrophyOutline,
  UnlockOutline,
  UserAddOutline,
  UserOutline,
  WarningOutline,
} from '@ant-design/icons-angular/icons';
import { provideNzI18n, vi_VN } from 'ng-zorro-antd/i18n';
import { provideNzIcons } from 'ng-zorro-antd/icon';

import { routes } from './app.routes';
import { AuthService } from './core/api/auth.service';
import { authInterceptor } from './core/auth/auth.interceptor';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideAnimationsAsync(),
    provideRouter(routes),
    provideHttpClient(withInterceptors([authInterceptor])),
    provideAppInitializer(() => inject(AuthService).initialize()),
    provideNzI18n(vi_VN),
    provideNzIcons([
      AppstoreOutline,
      ArrowRightOutline,
      AuditOutline,
      BarChartOutline,
      BellOutline,
      BookOutline,
      CalendarOutline,
      CameraOutline,
      CheckCircleOutline,
      CheckSquareOutline,
      DeleteOutline,
      EditOutline,
      FileTextOutline,
      FormOutline,
      HomeOutline,
      InboxOutline,
      InfoCircleOutline,
      KeyOutline,
      LockOutline,
      LoginOutline,
      LogoutOutline,
      MailOutline,
      MenuOutline,
      PlusOutline,
      ReadOutline,
      ReloadOutline,
      RobotOutline,
      SearchOutline,
      SettingOutline,
      SolutionOutline,
      StarOutline,
      SwapOutline,
      TeamOutline,
      TrophyOutline,
      UnlockOutline,
      UserAddOutline,
      UserOutline,
      WarningOutline,
    ]),
  ],
};
